
#ifndef MUSCLE_MOVEMENT_H
#define MUSCLE_MOVEMENT_H

enum MuscleMovement {
	REST_POSITION, WRIST_FLEXION, WRIST_EXTENSION, RADIAL_DEVIATION, ULNAR_DEVIATION, FORARM_PRONATION, FORARM_SUPINATION, HAND_OPEN, HAND_CLOSE
};

#endif